name: Deploy via Terraform Cloud
on:
  workflow_dispatch:
  
jobs:
  plan:
    name: Create Plan in TFC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: OpenTofu Init with TFC
        working-directory: ./opentofu
        run: |
          tofu init
      
      - name: OpenTofu Validate
        working-directory: ./opentofu
        run: |
          tofu validate -no-color
      
      - name: OpenTofu Plan (Local execution, remote state)
        working-directory: ./opentofu
        env:
          TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
        run: |
          tofu plan -no-color
      
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: "./opentofu"
          format: "table"
          exit-code: 1
          ignore-unfixed: false
          severity: "CRITICAL,HIGH,MEDIUM"
